{% set name = "cyrsoxs" %}
{% set version = "1.1.7.0" %}
{% set sha = "3acaede7f027e8318a36d1b9bda0bfea74ac7d24e014ec115fb7ef547750a6a7" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/usnistgov/cyrsoxs/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  skip: True  # [not linux64]
  skip: True  # [cuda_compiler_version == "None"]
  number: 0

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}
    - cmake
    - make
    - libgomp
  host:
    - python
    - pybind11
    - pybind11-abi
    - hdf5
    - libgomp
    - libconfig
    - cuda-version {{ cuda_compiler_version }}  # [(cuda_compiler_version or "None") != "None"]
    - cuda-cudart-dev                           # [(cuda_compiler_version or "").startswith("12")]
    - libcufft-dev                              # [(cuda_compiler_version or "").startswith("12")]
    - libcublas-dev                             # [(cuda_compiler_version or "").startswith("12")]
    - libnpp-dev                                # [(cuda_compiler_version or "").startswith("12")]
  run:
    - libgomp
    - libconfig
    - python
test:
  imports:
    - CyRSoXS
about:
  home: https://github.com/usnistgov/cyrsoxs
  summary: Cy-RSoXS Forward Simulator for Resonant Soft X-Ray Scattering
  license: MIT
  license: NIST-PD
  license_family: MIT
  license_file: LICENSE
  doc_url: https://nrss.readthedocs.io/
  dev_url: https://github.com/usnistgov/cyrsoxs

extra:
  recipe-maintainers:
    - pbeaucage
    - pdudenas
    - delongchamp
