{% set name = "cyrsoxs" %}
{% set version = "1.1.6.0" %}
{% set sha = "bd9d75f924a4d83c48db6584ac1ccbf003ca399b03bca29fb90bfffe904fd0d4" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/usnistgov/cyrsoxs/archive/refs/tags/V{{ version }}.tar.gz
  sha256: {{ sha }}
  patches:
      - 0001-Add-windows-cutout-for-libconfig.patch

build:
  skip: True  # [py<37]
  skip: True  # [not linux64 and not win64]
  skip: True  # [cuda_compiler_version == "None"]
  number: 5

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - ninja  # [win]
    - cmake
    - make
    - libgomp  # [linux]
    - libconfig
  host:
    - python
    - pybind11
    - pybind11-abi
    - hdf5
    - libconfig
    - cuda-version {{ cuda_compiler_version }}  # [(cuda_compiler_version or "None") != "None"]
    - cuda-cudart-dev                           # [(cuda_compiler_version or "").startswith("12")]
    - libcufft-dev                              # [(cuda_compiler_version or "").startswith("12")]
    - libcublas-dev                             # [(cuda_compiler_version or "").startswith("12")]
    - libnpp-dev                                # [(cuda_compiler_version or "").startswith("12")]
  run:
    - libconfig
    - python
test:
  imports:
    - CyRSoXS
about:
  home: https://github.com/usnistgov/cyrsoxs
  summary: 'Cy-RSoXS Forward Simulator for Resonant Soft X-Ray Scattering'
  description: |
  license: MIT
  license: NIST-PD
  license_family: MIT
  license_file: LICENSE
  doc_url: https://nrss.readthedocs.io/
  dev_url: https://github.com/usnistgov/cyrsoxs

extra:
  recipe-maintainers:
    - pbeaucage
    - pdudenas
