{% set name = "cyrsoxs" %}
{% set version = "1.1.5.2" %}
{% set sha = "85b70f90808bf603a5e9c710f4f3b53d071716db1884faf61f3f585abce9e274" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/usnistgov/cyrsoxs/archive/refs/tags/V{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  skip: True  # [py<37]
  skip: True  # [not linux64 and not win64]
  skip: True  # [cuda_compiler_version == "None"]
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - make
    - libgomp  # [linux]
    - libconfig
  host:
    - python
    - pybind11
    - pybind11-abi
    - hdf5
    - libconfig
  run:
    - libconfig
    - python
test:
  imports:
    - CyRSoXS
about:
  home: https://github.com/usnistgov/cyrsoxs
  summary: 'Cy-RSoXS Forward Simulator for Resonant Soft X-Ray Scattering'
  description: |
  license: MIT
  license: NIST-PD
  license_family: MIT
  license_file: LICENSE
  doc_url: https://nrss.readthedocs.io/
  dev_url: https://github.com/usnistgov/cyrsoxs

extra:
  recipe-maintainers:
    - pbeaucage
    - pdudenas
