{% set name = "cyrsoxs" %}
{% set version = "1.1.8.0" %}
{% set sha = "c1b4b001ff56937881b2cef452f40e08c5a85900403ff86d527dcbbf5a994305" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/usnistgov/cyrsoxs/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  skip: True  # [not linux64 or cuda_compiler_version == "None"]
  number: 3

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}
    - cmake
    - make
    - libgomp
  host:
    - python
    - pybind11
    - pybind11-abi
    - hdf5
    - libgomp
    - libconfig
    - cuda-version {{ cuda_compiler_version }}  # [(cuda_compiler_version or "None") != "None"]
    - cuda-cudart-dev                           # [(cuda_compiler_version or "").startswith("12")]
    - libcufft-dev                              # [(cuda_compiler_version or "").startswith("12")]
    - libcublas-dev                             # [(cuda_compiler_version or "").startswith("12")]
    - libnpp-dev                                # [(cuda_compiler_version or "").startswith("12")]
  run:
    - libgomp
    - libconfig
    - python
test:
  imports:
    - CyRSoXS
about:
  home: https://github.com/usnistgov/cyrsoxs
  summary: Cy-RSoXS Forward Simulator for Resonant Soft X-Ray Scattering
  license: "MIT AND NIST-PD"
  license_family: MIT
  license_file: LICENSE
  doc_url: https://nrss.readthedocs.io/
  dev_url: https://github.com/usnistgov/cyrsoxs

extra:
  recipe-maintainers:
    - pbeaucage
    - pdudenas
    - delongchamp
